main: org.zkaleejoo.MaxStaff
version: ${project.version}
name: MaxStaff
author: ZkAleeJoo
api-version: 1.19

commands:
  maxstaff:
    description: Main MaxStaff command
    aliases: [staff, ms]
    permission: maxstaff.admin
  ban:
    description: Ban a player
    permission: maxstaff.punish.ban
    usage: /ban <player> [time] [reason]
  tempban:
    description: Temporarily ban a player
    permission: maxstaff.punish.ban
  mute:
    description: Mute a player
    permission: maxstaff.punish.mute
  tempmute:
    description: Temporarily mute a player
    permission: maxstaff.punish.mute
  kick:
    description: Kick a player
    permission: maxstaff.punish.kick
  unban:
    description: Unban a player
    permission: maxstaff.punish.unban
  unmute:
    description: Unmute a player
    permission: maxstaff.punish.unmute
  warn:
    description: Warn a player
    permission: maxstaff.punish.warn
  history:
    description: View sanction history
    permission: maxstaff.history
  vanish:
    description: Toggle invisibility
    permission: maxstaff.vanish
  ban-ip:
    description: Ban IP address
    permission: maxstaff.punish.banip
  tempban-ip:
    description: Temporarily ban IP address
    permission: maxstaff.punish.banip
  unban-ip:
    description: Unban IP address
    permission: maxstaff.punish.unbanip
  sc:
    description: Staff chat
    permission: maxstaff.staffchat
  cmdspy:
    description: Spy on commands
    permission: maxstaff.cmdspy
  chat:
    description: Manage global chat
    permission: maxstaff.chat.admin
  gamemode:
    description: Gamemode selector
    aliases: [gm]
    permission: maxstaff.gamemode
  alts:
    description: View alt accounts
    aliases: [alt, accs]
    permission: maxstaff.alts
  sanction:
    description: Advanced sanction menu
    permission: maxstaff.punish
  freeze:
    description: Freeze a player
    aliases: [ss]
    permission: maxstaff.freeze
  unfreeze:
    description: Unfreeze a player
    aliases: [uss]
    permission: maxstaff.freeze
    
permissions:
  maxstaff.admin:
    description: Full access to MaxStaff and administrative commands.
    default: op
    children:
      maxstaff.mode: true
      maxstaff.punish.ban: true
      maxstaff.punish.mute: true 
      maxstaff.punish.kick: true
      maxstaff.punish.warn: true
      maxstaff.punish.unban: true
      maxstaff.punish.unmute: true
      maxstaff.see.vanish: true
      maxstaff.history: true
      maxstaff.vanish: true
      maxstaff.punish.banip: true
      maxstaff.punish.unbanip: true
      maxstaff.staffchat: true
      maxstaff.cmdspy: true
      maxstaff.chat.admin: true
      maxstaff.gamemode: true
      maxstaff.alts: true
      maxstaff.punish: true
      maxstaff.freeze: true
  maxstaff.punish.ban:
    description: Allows using /ban and /tempban.
    default: op
  maxstaff.punish.mute:
    description: Allows using /mute and /tempmute.
    default: op
  maxstaff.punish.kick:
    description: Allows using /kick.
    default: op
  maxstaff.punish.warn:
    description: Allows using /warn.
    default: op
  maxstaff.punish.unban:
    description: Allows using /unban.
    default: op
  maxstaff.punish.unmute:
    description: Allows using /unmute.
    default: op
  maxstaff.mode:
    description: Allows entering staff mode (/staff mode).
    default: op
  maxstaff.see.vanish:
    description: Allows seeing other staff members in vanish.
    default: op
  maxstaff.history:
    description: Allows using /history.
    default: op
  maxstaff.vanish:
    description: Allows using the /vanish command.
    default: op
  maxstaff.punish.banip:
    description: Allows using /ban-ip and /tempban-ip.
    default: op
  maxstaff.punish.unbanip:
    description: Allows using /unban-ip.
    default: op
  maxstaff.staffchat:
    description: Allows using and viewing staff chat.
    default: op
  maxstaff.cmdspy:
    description: Allows using /cmdspy to spy on commands.
    default: op
  maxstaff.chat.admin:
    description: Allows muting and clearing global chat.
    default: op
  maxstaff.gamemode:
    description: Allows using /gm to open the GUI.
    default: op
  maxstaff.alts:
    description: Allows using the alt tracking system.
    default: op
  maxstaff.punish:
    description: Allows using /sanction to open the advanced sanction menu.
    default: op
  maxstaff.freeze:
    description: Allows using /freeze and /unfreeze.
    default: op