main: org.zkaleejoo.MaxStaff
version: ${project.version}
name: MaxStaff
author: ZkAleeJoo
api-version: 1.19

commands:
  maxstaff:
    description: Comando principal de MaxStaff
    aliases: [staff, ms]
  ban:
    description: Banear jugador (Permanente o Temporal)
  tempban:
    description: Banear temporalmente a un jugador
  mute:
    description: Silenciar jugador (Permanente o Temporal)
  tempmute:
    description: Silenciar temporalmente a un jugador
  kick:
    description: Expulsar jugador del servidor
  unban:
    description: Perdonar el baneo de un jugador
  unmute:
    description: Devolver el habla a un jugador
  warn:
    description: Enviar una advertencia a un jugador
  history:
    description: Ver el historial de sanciones de un jugador
  vanish:
    description: Alterna tu invisibilidad ante otros jugadores.
  ban-ip:
    description: Banear la IP de un jugador de forma permanente.
  tempban-ip:
    description: Banear temporalmente la IP de un jugador
  unban-ip:
    description: Desbanear una IP
  sc:
    description: Chat privado para miembros del Staff
  cmdspy:
    description: Espía los comandos de los jugadores en tiempo real.
  chat:
    description: Gestiona el chat global (mute/clear)
  gamemode:
    description: Abre el selector visual de modo de juego.
    aliases: [gm]
  alts:
    description: Ver cuentas alternativas de un jugador.
    aliases: [alt, accs]
  sanction:
    description: Opens the advanced sanction menu for a player.
  freeze:
    description: Congela a un jugador para revisión.
    aliases: [ss]
  unfreeze:
    description: Descongela a un jugador.
    aliases: [uss]
    
permissions:
  maxstaff.admin:
    description: Acceso total a MaxStaff y comandos administrativos.
    default: op
    children:
      maxstaff.mode: true
      maxstaff.punish.ban: true
      maxstaff.punish.mute: true 
      maxstaff.punish.kick: true
      maxstaff.punish.warn: true
      maxstaff.punish.unban: true
      maxstaff.punish.unmute: true
      maxstaff.see.vanish: true
      maxstaff.history: true
      maxstaff.vanish: true
      maxstaff.punish.banip: true
      maxstaff.punish.unbanip: true
      maxstaff.staffchat: true
      maxstaff.cmdspy: true
      maxstaff.chat.admin: true
      maxstaff.gamemode: true
      maxstaff.alts: true
      maxstaff.punish: true
      maxstaff.freeze: true
  maxstaff.punish.ban:
    description: Permite usar /ban y /tempban.
    default: op
  maxstaff.punish.mute:
    description: Permite usar /mute y /tempmute.
    default: op
  maxstaff.punish.kick:
    description: Permite usar /kick.
    default: op
  maxstaff.punish.warn:
    description: Permite usar /warn.
    default: op
  maxstaff.punish.unban:
    description: Permite usar /unban.
    default: op
  maxstaff.punish.unmute:
    description: Permite usar /unmute.
    default: op
  maxstaff.mode:
    description: Permite entrar en modo staff (/staff mode).
    default: op
  maxstaff.see.vanish:
    description: Permite ver a otros miembros del staff en vanish.
    default: op
  maxstaff.history:
    description: Permite usar /history.
    default: op
  maxstaff.vanish:
    description: Permite usar el comando /vanish.
    default: op
  maxstaff.punish.banip:
    description: Permite usar /ban-ip y /tempban-ip
    default: op
  maxstaff.punish.unbanip:
    description: Permite usar /unban-ip
    default: op
  maxstaff.staffchat:
    description: Permite usar y ver el chat de staff.
    default: op
  maxstaff.cmdspy:
    description: Permite usar /cmdspy para espiar comandos.
    default: op
  maxstaff.chat.admin:
    description: Permite silenciar y limpiar el chat global.
    default: op
  maxstaff.gamemode:
    description: Permite usar /gm para abrir el GUI.
    default: op
  maxstaff.alts:
    description: Permite usar el sistema de rastreo de alts.
    default: op
  maxstaff.punish:
    description: Permiso usar /sanction para abrir el menú avanzado de sanciones.
    default: op
  maxstaff.freeze:
    description: Permite usar /freeze y /unfreeze.
    default: op