main: org.zkaleejoo.MaxStaff
version: ${project.version}
name: MaxStaff
author: ZkAleeJoo
api-version: 1.20

commands:
  maxstaff:
    description: Comando principal de MaxStaff
    aliases: [staff, ms]
  ban:
    description: Banear jugador
  tempban:
    description: Banear temporalmente
  mute:
    description: Mutear jugador
  tempmute:
    description: Mutear temporalmente
  kick:
    description: Expulsar jugador
  unban:
    description: Desbanear
  unmute:
    description: Desmutear
  warn:
    description: Advertir jugador

permissions:
  maxstaff.admin:
    description: Permisos de administrador para MaxStaff
    default: op