main: org.zkaleejoo.MaxStaff
version: ${project.version}
name: MaxStaff
author: ZkAleeJoo
api-version: 1.19

commands:
  maxstaff:
    description: Comando principal de MaxStaff
    aliases: [staff, ms]
  ban:
    description: Banear jugador (Permanente o Temporal)
  tempban:
    description: Banear temporalmente a un jugador
  mute:
    description: Silenciar jugador (Permanente o Temporal)
  tempmute:
    description: Silenciar temporalmente a un jugador
  kick:
    description: Expulsar jugador del servidor
  unban:
    description: Perdonar el baneo de un jugador
  unmute:
    description: Devolver el habla a un jugador
  warn:
    description: Enviar una advertencia a un jugador
  history:
    description: Ver el historial de sanciones de un jugador
  vanish:
    description: Alterna tu invisibilidad ante otros jugadores.
  ban-ip:
    description: Banear la IP de un jugador de forma permanente.
  tempban-ip:
    description: Banear temporalmente la IP de un jugador
  unban-ip:
    description: Desbanear una IP
    
permissions:
  maxstaff.admin:
    description: Acceso total a MaxStaff y comandos administrativos.
    default: op
    children:
      maxstaff.mode: true
      maxstaff.punish.ban: true
      maxstaff.punish.mute: true
      maxstaff.punish.kick: true
      maxstaff.punish.warn: true
      maxstaff.punish.unban: true
      maxstaff.punish.unmute: true
      maxstaff.see.vanish: true
      maxstaff.history: true
      maxstaff.vanish: true
      maxstaff.punish.banip: true
      maxstaff.punish.unbanip: true
  maxstaff.punish.ban:
    description: Permite usar /ban y /tempban.
    default: op
  maxstaff.punish.mute:
    description: Permite usar /mute y /tempmute.
    default: op
  maxstaff.punish.kick:
    description: Permite usar /kick.
    default: op
  maxstaff.punish.warn:
    description: Permite usar /warn.
    default: op
  maxstaff.punish.unban:
    description: Permite usar /unban.
    default: op
  maxstaff.punish.unmute:
    description: Permite usar /unmute.
    default: op
  maxstaff.mode:
    description: Permite entrar en modo staff (/staff mode).
    default: op
  maxstaff.see.vanish:
    description: Permite ver a otros miembros del staff en vanish.
    default: op
  maxstaff.history:
    description: Permite usar /history.
    default: op
  maxstaff.vanish:
    description: Permite usar el comando /vanish.
    default: op
  maxstaff.punish.banip:
    description: Permite usar /ban-ip y /tempban-ip
    default: op
  maxstaff.punish.unbanip:
    description: Permite usar /unban-ip
    default: op