main: org.zkaleejoo.MaxStaff
version: ${project.version}
name: MaxStaff
author: ZkAleeJoo
api-version: 1.19

commands:
  maxstaff:
    description: Main MaxStaff command
    aliases: [staff, ms]
  ban:
    description: Ban a player (Permanent or Temporary)
  tempban:
    description: Temporarily ban a player
  mute:
    description: Mute a player (Permanent or Temporary)
  tempmute:
    description: Temporarily mute a player
  kick:
    description: Kick a player from the server
  unban:
    description: Unban a player
  unmute:
    description: Unmute a player
  warn:
    description: Send a warning to a player
  history:
    description: View a player's sanction history
  vanish:
    description: Toggle your invisibility to other players
  ban-ip:
    description: Permanently ban a player's IP
  tempban-ip:
    description: Temporarily ban a player's IP
  unban-ip:
    description: Unban an IP
  sc:
    description: Private chat for Staff members
  cmdspy:
    description: Spy on player commands in real time
  chat:
    description: Manage global chat (mute/clear)
  gamemode:
    description: Open the gamemode selector
    aliases: [gm]
  alts:
    description: View a player's alternate accounts
    aliases: [alt, accs]
  sanction:
    description: Opens the advanced sanction menu for a player
  freeze:
    description: Freeze a player for review
    aliases: [ss]
  unfreeze:
    description: Unfreeze a player
    aliases: [uss]
    
permissions:
  maxstaff.admin:
    description: Full access to MaxStaff and administrative commands.
    default: op
    children:
      maxstaff.mode: true
      maxstaff.punish.ban: true
      maxstaff.punish.mute: true 
      maxstaff.punish.kick: true
      maxstaff.punish.warn: true
      maxstaff.punish.unban: true
      maxstaff.punish.unmute: true
      maxstaff.see.vanish: true
      maxstaff.history: true
      maxstaff.vanish: true
      maxstaff.punish.banip: true
      maxstaff.punish.unbanip: true
      maxstaff.staffchat: true
      maxstaff.cmdspy: true
      maxstaff.chat.admin: true
      maxstaff.gamemode: true
      maxstaff.alts: true
      maxstaff.punish: true
      maxstaff.freeze: true
  maxstaff.punish.ban:
    description: Allows using /ban and /tempban.
    default: op
  maxstaff.punish.mute:
    description: Allows using /mute and /tempmute.
    default: op
  maxstaff.punish.kick:
    description: Allows using /kick.
    default: op
  maxstaff.punish.warn:
    description: Allows using /warn.
    default: op
  maxstaff.punish.unban:
    description: Allows using /unban.
    default: op
  maxstaff.punish.unmute:
    description: Allows using /unmute.
    default: op
  maxstaff.mode:
    description: Allows entering staff mode (/staff mode).
    default: op
  maxstaff.see.vanish:
    description: Allows seeing other staff members in vanish.
    default: op
  maxstaff.history:
    description: Allows using /history.
    default: op
  maxstaff.vanish:
    description: Allows using the /vanish command.
    default: op
  maxstaff.punish.banip:
    description: Allows using /ban-ip and /tempban-ip.
    default: op
  maxstaff.punish.unbanip:
    description: Allows using /unban-ip.
    default: op
  maxstaff.staffchat:
    description: Allows using and viewing staff chat.
    default: op
  maxstaff.cmdspy:
    description: Allows using /cmdspy to spy on commands.
    default: op
  maxstaff.chat.admin:
    description: Allows muting and clearing global chat.
    default: op
  maxstaff.gamemode:
    description: Allows using /gm to open the GUI.
    default: op
  maxstaff.alts:
    description: Allows using the alt tracking system.
    default: op
  maxstaff.punish:
    description: Allows using /sanction to open the advanced sanction menu.
    default: op
  maxstaff.freeze:
    description: Allows using /freeze and /unfreeze.
    default: op